### ISSUE TITLE
keyboard interrupts might get dropped under heavy load

### ISSUE THREAD

**Issue by sherhut** [djhworld/gomeboycolor#43]
Under heavy load (like when running using webassembly in Chrome), the processing of keyboard interrupts might swallow key events. The implementation relies on the scheduler to ensure that the cpu go-routine runs in between key-up and key-down events. This might not be the case as there is no guaranteed scheduling order.

While this is an anomaly of a specific scheduling, it would be nice to guard against this by delaying state changes of keys until after the next time the cpu had a chance to process them.

**Comment by djhworld** [comment]
Thanks, I'm looking into this area at the moment as I'm seeing the same (dropped keyboard events) on Firefox too - although  at higher frame rates than chrome. 

I figured it would be some scheduling/contention issue due to the lack of threading in WASM. 

Will keep this issue open and update my findings if I get anything

**Comment by djhworld** [comment]
I've resolved the keyboard problem this by wrapping the `doFrame` in a `setTimeout` (see https://github.com/djhworld/gomeboycolor-wasm/blob/master/main.go#L47) 

Games can now be played without those lost keyboard events! https://djhworld.github.io/demos/gomeboycolor/
